from pathlib import Path
from typing import List
from ..models import AnalysisResult

class MarkdownReporter:
    def render(self, global_score: int, results: List[AnalysisResult], output_path: Path):
        lines = []
        lines.append("# Repository Health Report\n")
        
        # Determine health color/status
        status = "🟢 Excellent" if global_score >= 80 else "🟡 Moderate" if global_score >= 60 else "🔴 Poor"
        lines.append(f"**Score:** {global_score}/100 ({status})\n")
        
        lines.append("## Metrics\n")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        
        issues = []
        suggestions = []
        
        # Collect data
        for result in results:
            for metric in result.metrics:
                val = f"{metric.value:.2g}" if isinstance(metric.value, float) else str(metric.value)
                name = metric.name.replace('_', ' ').capitalize()
                lines.append(f"| {name} | {val} |")
                
            issues.extend(result.issues)
            suggestions.extend(result.suggestions)
            
        lines.append("\n## Issues\n")
        if not issues:
            lines.append("✅ No issues detected!\n")
        else:
            for issue in issues:
                lines.append(f"- **{issue.category}**: {issue.message}")
        
        lines.append("\n## Suggestions\n")
        if not suggestions:
            lines.append("✅ Keep up the good work!\n")
        else:
            for sug in list(dict.fromkeys(suggestions)):
                lines.append(f"- {sug}")
                
        lines.append("\n---\n*Generated by [repo-health](https://github.com/NarimaneBr/repo-health)*\n")
        
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
